# Generated by Django 3.2.6 on 2022-04-18 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('earn_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.profile')),
            ],
        ),
    ]
